### pytest  file that sets configuration settings for the test ###

[pytest]
addopts = --html=reports/report.html
testpaths = tests
markers =
    e2e: marks tests as end-to-end
    integration: marks tests as integration tests
    unit: marks tests as unit tests
